/**
 * Test: Brain Gather module
 * Run: bun run test/test-brain-gather.ts
 */

import { parseCheckpoint, scanSessionDirs, groupMemoriesByCategory, gatherBrainData } from "../src/memory/brain-gather"
import type { Memory, MemoryCategory } from "../src/memory/types"
import { MemoryStore } from "../src/memory/store"
import { mkdirSync, rmSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const TEST_DIR = "/tmp/powerpack-test-brain"
const TEST_SESSIONS = `${TEST_DIR}/sessions`
const TEST_PROJECT = `${TEST_DIR}/project`

let passed = 0
let failed = 0

function assert(condition: boolean, msg: string) {
  if (condition) {
    passed++
    console.log(`  ✓ ${msg}`)
  } else {
    failed++
    console.log(`  ✗ ${msg}`)
  }
}

function assertEq(a: any, b: any, msg: string) {
  assert(a === b, `${msg} (got ${a}, expected ${b})`)
}

function section(name: string) {
  console.log(`\n--- ${name} ---`)
}

// === Setup ===
rmSync(TEST_DIR, { recursive: true, force: true })
mkdirSync(TEST_SESSIONS, { recursive: true })
mkdirSync(TEST_PROJECT, { recursive: true })

// === parseCheckpoint ===
section("parseCheckpoint")

const sampleCheckpoint = `Topic: Fix the auth token bug

# Session checkpoint
_Generated by checkpoint writer_

## §1 Active intent
> "fix the token expiry bug"

## §2 Next concrete action
Apply the one-line fix at auth.ts:87

## §3 Directives (this session)
- No execSync with user strings

## §4 Task tree
- ✅ Phase 1: Investigation complete
- 🔵 Phase 2: Apply fix

## §5 Current work
Fixed token expiry bug in auth.ts:87

## §6 Files and code sections
- src/auth.ts:87 — was checking iat, should check exp

## §7 Discovered knowledge (cross-task)
- Token timestamps are in seconds, Date.now() in ms

## §8 Errors and fixes
- Actor tool context param must be omitted

## §9 Live resources
- Git: main branch

## §10 Design decisions
- Use exp field not iat for token validation

## §11 Open notes
- Consider adding token refresh middleware`

const parsed = parseCheckpoint(sampleCheckpoint)
assertEq(parsed.topic, "Fix the auth token bug", "parses topic from first line")
assert(parsed.sections["§1 Active intent"] !== undefined, "sections contain §1 Active intent")
assert(parsed.sections["§2 Next concrete action"] !== undefined, "sections contain §2 Next concrete action")
assert(parsed.sections["§3 Directives (this session)"] !== undefined, "sections contain §3 Directives")
assert(parsed.sections["§4 Task tree"] !== undefined, "sections contain §4 Task tree")
assert(parsed.sections["§5 Current work"] !== undefined, "sections contain §5 Current work")
assert(parsed.sections["§6 Files and code sections"] !== undefined, "sections contain §6 Files and code sections")
assert(parsed.sections["§7 Discovered knowledge (cross-task)"] !== undefined, "sections contain §7 Discovered knowledge")
assert(parsed.sections["§8 Errors and fixes"] !== undefined, "sections contain §8 Errors and fixes")
assert(parsed.sections["§9 Live resources"] !== undefined, "sections contain §9 Live resources")
assert(parsed.sections["§10 Design decisions"] !== undefined, "sections contain §10 Design decisions")
assert(parsed.sections["§11 Open notes"] !== undefined, "sections contain §11 Open notes")
assert(parsed.sections["§4 Task tree"]!.includes("Phase 1"), "§4 Task tree contains Phase 1")
assert(parsed.sections["§4 Task tree"]!.includes("Phase 2"), "§4 Task tree contains Phase 2")
assert(parsed.sections["§11 Open notes"]!.includes("token refresh middleware"), "§11 Open notes contains token refresh middleware")

// Empty string
const emptyParsed = parseCheckpoint("")
assertEq(emptyParsed.topic, "", "empty string returns empty topic")
assertEq(Object.keys(emptyParsed.sections).length, 0, "empty string returns empty sections")

// No topic line
const noTopicParsed = parseCheckpoint("## §1 Active intent\nhello")
assertEq(noTopicParsed.topic, "", "missing Topic line returns empty topic")
assert(noTopicParsed.sections["§1 Active intent"] !== undefined, "still parses sections without topic")

// === scanSessionDirs ===
section("scanSessionDirs")

mkdirSync(`${TEST_SESSIONS}/ses_abc123`, { recursive: true })
mkdirSync(`${TEST_SESSIONS}/ses_def456`, { recursive: true })
mkdirSync(`${TEST_SESSIONS}/ses_ghi789`, { recursive: true })
writeFileSync(`${TEST_SESSIONS}/ses_abc123/checkpoint.md`, "Topic: Test\n## §1 Active intent\nfoo")
writeFileSync(`${TEST_SESSIONS}/ses_def456/checkpoint.md`, "Topic: Test2\n## §1 Active intent\nbar")
writeFileSync(`${TEST_SESSIONS}/ses_ghi789/notes.md`, "just notes, no checkpoint")

const checkpoints = scanSessionDirs(TEST_DIR)
assertEq(checkpoints.length, 2, "finds exactly 2 checkpoint files")
assert(checkpoints.some((p) => p.includes("ses_abc123")), "includes ses_abc123")
assert(checkpoints.some((p) => p.includes("ses_def456")), "includes ses_def456")
assert(!checkpoints.some((p) => p.includes("ses_ghi789")), "skips session without checkpoint.md")

// Non-existent directory
const emptyCheckpoints = scanSessionDirs("/tmp/nonexistent-powerpack-dir-xyz")
assertEq(emptyCheckpoints.length, 0, "non-existent directory returns empty array")

// === groupMemoriesByCategory ===
section("groupMemoriesByCategory")

const memories: Memory[] = [
  { id: 1, category: "ARCHITECTURE", content: "Use plugin hooks", projectPath: "/p", normalizedHash: "a", importance: 50, scope: "project", sourceSessionId: null, sourceType: "manual", seenCount: 0, retrievalCount: 0, createdAt: 0, updatedAt: 0, lastSeenAt: 0, lastRetrievedAt: null, status: "active", expiresAt: null, payloadType: null, payload: null },
  { id: 2, category: "BUG_FIXES", content: "Fixed null deref", projectPath: "/p", normalizedHash: "b", importance: 50, scope: "project", sourceSessionId: null, sourceType: "manual", seenCount: 0, retrievalCount: 0, createdAt: 0, updatedAt: 0, lastSeenAt: 0, lastRetrievedAt: null, status: "active", expiresAt: null, payloadType: null, payload: null },
  { id: 3, category: "ARCHITECTURE", content: "SQLite for storage", projectPath: "/p", normalizedHash: "c", importance: 50, scope: "project", sourceSessionId: null, sourceType: "manual", seenCount: 0, retrievalCount: 0, createdAt: 0, updatedAt: 0, lastSeenAt: 0, lastRetrievedAt: null, status: "active", expiresAt: null, payloadType: null, payload: null },
]

const grouped = groupMemoriesByCategory(memories)
assertEq(grouped["ARCHITECTURE"].length, 2, "ARCHITECTURE has 2 items")
assertEq(grouped["BUG_FIXES"].length, 1, "BUG_FIXES has 1 item")
assertEq(grouped["CONSTRAINTS"].length, 0, "CONSTRAINTS has 0 items (empty array present)")

// Empty array
const emptyGrouped = groupMemoriesByCategory([])
assertEq(emptyGrouped["ARCHITECTURE"].length, 0, "empty array returns empty per-category arrays")
assertEq(emptyGrouped["USER_PREFERENCES"].length, 0, "empty array covers all categories")

// === gatherBrainData integration ===
section("gatherBrainData integration")

// Create a DB with some memories
const dbPath = `${TEST_PROJECT}/.mimocode`
mkdirSync(dbPath, { recursive: true })
const store = new MemoryStore(`${dbPath}/memory.db`)
store.insert({ projectPath: TEST_PROJECT, category: "ARCHITECTURE", content: "Test memory one", importance: 80 })
store.insert({ projectPath: TEST_PROJECT, category: "BUG_FIXES", content: "Test memory two", importance: 50 })

const brainData = gatherBrainData(TEST_PROJECT)
assert(Array.isArray(brainData.sessions), "sessions is an array")
assert(typeof brainData.sessions.length === "number", "sessions has a length property")
assert(Array.isArray(brainData.memories), "memories is an array")
assert(brainData.memories.length >= 2, "memories includes inserted entries")

// Verify memories include both categories
const cats = brainData.memories.map((m) => m.category)
assert(cats.includes("ARCHITECTURE"), "memories include ARCHITECTURE entries")
assert(cats.includes("BUG_FIXES"), "memories include BUG_FIXES entries")

assert(typeof brainData.graph.stats === "object", "graph.stats is an object")
assertEq(typeof brainData.graph.stats.totalNodes, "number", "graph.stats.totalNodes is a number")
assertEq(typeof brainData.graph.stats.totalEdges, "number", "graph.stats.totalEdges is a number")

// Missing DB — should not crash
const missingProject = `${TEST_PROJECT}-nonexistent`
mkdirSync(missingProject, { recursive: true })
const missingData = gatherBrainData(missingProject)
assertEq(missingData.memories.length, 0, "missing DB returns empty memories")
assertEq(missingData.graph.nodes.length, 0, "missing DB returns empty graph nodes")

// === Cleanup ===
rmSync(TEST_DIR, { recursive: true, force: true })

console.log(`\n=== Brain Gather Tests: ${passed} passed, ${failed} failed ===`)
process.exit(failed > 0 ? 1 : 0)
